get:
  operationId: GetProductByID
  summary: Get a product by ID
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1
  responses:
    '200':
      $ref: '../responses/ProductResponse.yaml'
    '400':
      $ref: '../responses/ErrorResponse.yaml'
    '404':
      $ref: '../responses/ErrorResponse.yaml'
