get:
  operationId: SearchProducts
  summary: Search products
  parameters:
    - in: query
      name: q
      schema:
        type: string
        minLength: 3
    - in: query
      name: page
      schema:
        type: integer
        minimum: 1
        default: 1
    - in: query
      name: pageSize
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
  responses:
    '200':
      $ref: '../responses/ProductListResponse.yaml'
    '400':
      $ref: '../responses/ErrorResponse.yaml'
