apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gopractice-dev
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: gopractice-dev
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-secret
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ['pg_isready','-U','app','-d','productdb']
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pgdata
          emptyDir: {}
