apiVersion: v1
kind: Service
metadata:
  name: product-query-svc
  namespace: marketplace-dev
spec:
  selector:
    app: product-query-svc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-query-svc
  namespace: marketplace-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-query-svc
  template:
    metadata:
      labels:
        app: product-query-svc
    spec:
      initContainers:
        - name: migrate
          image: product-query-svc:dev
          imagePullPolicy: IfNotPresent
          args: ["-migrate"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: pg-secret
      containers:
        - name: product-query-svc
          image: product-query-svc:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
