image:
  repository: product-query-svc
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  HTTP_ADDRESS: ":8080"
  # App listen address; DATABASE_URL now comes from .Values.database.secret when enabled
  DATABASE_URL: "postgres://app:app_password@postgres.marketplace-dev.svc.cluster.local:5432/productdb?sslmode=disable" # fallback only

podAnnotations: {}
replicaCount: 1
nameOverride: ""
fullnameOverride: ""

migrations:
  enabled: true
  image: migrate/migrate:latest

database:
  # Use an existing Secret to inject DATABASE_URL
  secret:
    enabled: true
    name: product-query-svc-db
    key: DATABASE_URL
    create: false
  # If create=true, a Secret will be created with this URL as stringData.DATABASE_URL
  url: "postgres://app:app_password@postgres.marketplace-dev.svc.cluster.local:5432/productdb?sslmode=disable"
