image:
  repository: product-query-svc
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  HTTP_ADDRESS: ":8080"
  # Prefer injecting a DATABASE_URL via secret; fallback provided here for dev
  DATABASE_URL: "postgres://app:app_password@postgres.marketplace-dev.svc.cluster.local:5432/productdb?sslmode=disable"

podAnnotations: {}
replicaCount: 1
nameOverride: ""
fullnameOverride: ""

migrations:
  enabled: true
  image: migrate/migrate:latest
