type: object
properties:
  items:
    type: array
    items:
      $ref: './Product.yaml'    # 每一项是一个 Product
  page:
    type: integer
    minimum: 1
  pageSize:
    type: integer
    minimum: 1
    maximum: 100
  total:
    type: integer
    minimum: 0
required: [items, page, pageSize, total]
