type: object
properties:
  items:
    type: array
    items:
      $ref: '#/components/schemas/Product'
  page:
    type: integer
  pageSize:
    type: integer
  total:
    type: integer
required: [items, page, pageSize, total]
