{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "product-query-svc.fullname" . }}-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: {{ include "product-query-svc.name" . }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.migrations.image | quote }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"]
          args:
            - migrate -path /migrations -database "$DATABASE_URL" up
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
          volumeMounts:
            - name: migrations
              mountPath: /migrations
              readOnly: true
      volumes:
        - name: migrations
          configMap:
            name: {{ include "product-query-svc.fullname" . }}-migrations
{{- end }}

