openapi: 3.0.0
info:
  title: Marketplace Demo API
  version: 1.0.0
tags:
  - name: Products
    description: Product query and management endpoints

paths:
  /products/{id}:
    $ref: './paths/products/get_by_id.yaml'
  /products/search:
    $ref: './paths/products/search.yaml'
  /products:
    $ref: './paths/products/create.yaml'

components:
  schemas:
    Product:
      $ref: './schemas/Product.yaml'
    ProductCreate:
      $ref: './schemas/ProductCreate.yaml'
    ProductList:
      $ref: './schemas/ProductList.yaml'
    Error:
      $ref: './schemas/Error.yaml'
