openapi: 3.0.0
info:
  title: gopractice Demo API
  version: 1.0.0
tags:
  - name: Products
    description: Product query and management endpoints
  - name: Users
    description: User account retrieval endpoints
  - name: Comments
    description: Product comment management endpoints

paths:
  /products/{id}:
    $ref: './paths/products/item.yaml'
  /products/search:
    $ref: './paths/products/search.yaml'
  /products:
    $ref: './paths/products/collection.yaml'
  /products/{productId}/comments:
    $ref: './paths/products/comments.yaml'
  /products/{productId}/comments/{commentId}:
    $ref: './paths/products/comment-item.yaml'
  /users/{id}:
    $ref: './paths/users/item.yaml'



components:
  schemas:
    Product:
      $ref: './schemas/Product.yaml'
    ProductCreate:
      $ref: './schemas/ProductCreate.yaml'
    ProductList:
      $ref: './schemas/ProductList.yaml'
    Comment:
      $ref: './schemas/Comment.yaml'
    CommentCreate:
      $ref: './schemas/CommentCreate.yaml'
    CommentUpdate:
      $ref: './schemas/CommentUpdate.yaml'
    CommentList:
      $ref: './schemas/CommentList.yaml'
    User:
      $ref: './schemas/User.yaml'
    Error:
      $ref: './schemas/Error.yaml'
