openapi: 3.0.0
info:
  title: Marketplace Demo API
  version: 1.0.0

paths:
  /products/{id}:
    $ref: './paths/products_by_id.yaml'
  /products/search:
    $ref: './paths/products_search.yaml'
  /products:
    $ref: './paths/products_create.yaml'

components:
  schemas:
    Product:
      $ref: './schemas/Product.yaml'
    ProductCreate:
      $ref: './schemas/ProductCreate.yaml'
    ProductList:
      $ref: './schemas/ProductList.yaml'
    Error:
      $ref: './schemas/Error.yaml'

  responses:
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
