openapi: 3.0.0
info:
  title: Marketplace Demo API
  version: 1.0.0
servers:
  - url: https://example.com

paths:
  /products/{id}:
    $ref: 'paths/products_by_id.yaml'
  /products/search:
    $ref: 'paths/products_search.yaml'

components:
  schemas:
    Product:
      $ref: './schemas/Product.yaml'
    ProductList:
      $ref: './schemas/ProductList.yaml'
    Error:
      $ref: './schemas/Error.yaml'

