openapi: 3.0.0
info:
  title: Marketplace Demo API
  version: 1.0.0
tags:
  - name: Products
    description: Product query and management endpoints
  - name: Users
    description: User account retrieval endpoints

paths:
  /products/{id}:
    $ref: './paths/products/item.yaml'
  /products/search:
    $ref: './paths/products/search.yaml'
  /products:
    $ref: './paths/products/collection.yaml'
  /users/{id}:
    $ref: './paths/users/item.yaml'
  /users:
    $ref: './paths/users/collection.yaml'




components:
  schemas:
    Product:
      $ref: './schemas/Product.yaml'
    ProductCreate:
      $ref: './schemas/ProductCreate.yaml'
    ProductList:
      $ref: './schemas/ProductList.yaml'
    User:
      $ref: './schemas/User.yaml'
    UserCreate:
      $ref: './schemas/UserCreate.yaml'
    Error:
      $ref: './schemas/Error.yaml'
